# -*- coding: utf-8 -*-
"""Week-8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19hB_7OTpRThDK4BeB4XLobzWh7ztja6k
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_curve, roc_auc_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import matplotlib.pyplot as plt
import numpy as np

# Assume you have a DataFrame 'df' with features and a binary 'target' column
# For demonstration purposes, let's create a sample DataFrame
data = {'feature1': np.random.rand(100),
        'feature2': np.random.rand(100),
        'categorical_feature': np.random.choice(['A', 'B', 'C'], size=100),
        'target': np.random.randint(0, 2, size=100)}
df = pd.DataFrame(data)

# Separate features (X) and target (y)
X = df.drop('target', axis=1)
y = df['target']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Train a Logistic Regression model on 'feature1'
model_single_feature = LogisticRegression()
model_single_feature.fit(X_train[['feature1']], y_train)

# Get probability predictions on the test set
y_prob_single = model_single_feature.predict_proba(X_test[['feature1']])[:, 1]

print("Default threshold (0.5):")
y_pred_default = (y_prob_single > 0.5).astype(int)
print(f"  Accuracy: {accuracy_score(y_test, y_pred_default):.4f}")
print(f"  Precision: {precision_score(y_test, y_pred_default):.4f}")
print(f"  Recall: {recall_score(y_test, y_pred_default):.4f}")
print("-" * 30)

# Try a lower threshold (e.g., 0.3)
threshold_lower = 0.3
y_pred_lower = (y_prob_single > threshold_lower).astype(int)
print(f"Threshold: {threshold_lower}")
print(f"  Accuracy: {accuracy_score(y_test, y_pred_lower):.4f}")
print(f"  Precision: {precision_score(y_test, y_pred_lower):.4f}")
print(f"  Recall: {recall_score(y_test, y_pred_lower):.4f}")
print("-" * 30)

# Try a higher threshold (e.g., 0.7)
threshold_higher = 0.7
y_pred_higher = (y_prob_single > threshold_higher).astype(int)
print(f"Threshold: {threshold_higher}")
print(f"  Accuracy: {accuracy_score(y_test, y_pred_higher):.4f}")
print(f"  Precision: {precision_score(y_test, y_pred_higher):.4f}")
print(f"  Recall: {recall_score(y_test, y_pred_higher):.4f}")

# Identify numerical and categorical features
numerical_features = X_train.select_dtypes(include=np.number).columns.tolist()
categorical_features = X_train.select_dtypes(include='object').columns.tolist()

# Create preprocessing pipelines for numerical and categorical features
numerical_transformer = StandardScaler()
categorical_transformer = OneHotEncoder(handle_unknown='ignore')

# Combine preprocessing steps using ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)])

# Create the full pipeline with preprocessing and Logistic Regression
model_all_features = Pipeline(steps=[('preprocessor', preprocessor),
                                     ('classifier', LogisticRegression(random_state=42))])

# Train the model
model_all_features.fit(X_train, y_train)

# Get probability predictions on the test set
y_prob_all = model_all_features.predict_proba(X_test)[:, 1]

print("\nLogistic Regression on all features (default threshold 0.5):")
y_pred_all_default = (y_prob_all > 0.5).astype(int)
print(f"  Accuracy: {accuracy_score(y_test, y_pred_all_default):.4f}")
print(f"  Precision: {precision_score(y_test, y_pred_all_default):.4f}")
print(f"  Recall: {recall_score(y_test, y_pred_all_default):.4f}")

# Calculate ROC curve for the single-feature model
fpr_single, tpr_single, thresholds_single = roc_curve(y_test, y_prob_single)
auc_single = roc_auc_score(y_test, y_prob_single)

# Calculate ROC curve for the model with all features
fpr_all, tpr_all, thresholds_all = roc_curve(y_test, y_prob_all)
auc_all = roc_auc_score(y_test, y_prob_all)

# Plot the ROC curves
plt.figure(figsize=(8, 6))
plt.plot(fpr_single, tpr_single, label=f'Single Feature (AUC = {auc_single:.2f})')
plt.plot(fpr_all, tpr_all, label=f'All Features (AUC = {auc_all:.2f})')
plt.plot([0, 1], [0, 1], 'k--', label='Random Guessing')  # Diagonal line for random guessing
plt.xlabel('False Positive Rate (FPR)')
plt.ylabel('True Positive Rate (TPR)')
plt.title('ROC Curve Comparison')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

# Calculate ROC curve for the single-feature model
fpr_single, tpr_single, thresholds_single = roc_curve(y_test, y_prob_single)
auc_single = roc_auc_score(y_test, y_prob_single)

# Calculate ROC curve for the model with all features
fpr_all, tpr_all, thresholds_all = roc_curve(y_test, y_prob_all)
auc_all = roc_auc_score(y_test, y_prob_all)

# Plot the ROC curves
plt.figure(figsize=(8, 6))
plt.plot(fpr_single, tpr_single, label=f'Single Feature (AUC = {auc_single:.2f})')
plt.plot(fpr_all, tpr_all, label=f'All Features (AUC = {auc_all:.2f})')
plt.plot([0, 1], [0, 1], 'k--', label='Random Guessing')  # Diagonal line for random guessing
plt.xlabel('False Positive Rate (FPR)')
plt.ylabel('True Positive Rate (TPR)')
plt.title('ROC Curve Comparison')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()